export enum EPagesRoutes {
  Main = '/',
  Auth = '/auth',
  Registration = '/registration',
  Basket = '/basket',
  ProductDetail = '/productDetail',
  Profile = '/profile',
  CreateProduct = '/createProduct',
  Order = '/order',
  OrderHistory = '/orderHistory',
  PersonalAccount = '/personalAccount',
  UnauthorizedOrder = '/unauthorizedOrder',
  Collection = '/collection',
  Brand = '/brand',
  SearchResult = '/searchResult',
  Category = '/category',
  Sale = '/sale',
  Liked = '/liked',
}
